version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: node app.js 

  
volumes:
    db:
    node_modules: