version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file: .env
    volumes:
      - node_modules:/node_modules
    command: node app.js 
  
volumes:
    node_modules: